rockstar_games_launcher: new app
Kreyren/winetricks pull request #13
Opened 2019-11-06 00:03 UTC by Klairm

uwu

2019-11-06 11:36 UTC, Kreyren commented
Please make a merge request in `kreytricks:upstream` that is a branch synced with upstream assuming that we will be pushing in there.

2019-11-06 11:37 UTC, Kreyren commented
What is the status on this? Did you made the function for GTA V yet?

2019-11-07 22:27 UTC, Klairm commented
We have rockstar-games-launcher.exe which extracts files in C:/Program Files/rockstarsomethibg and which doesnt work with condlg32 provides with wine so it wont extract the files and permanent fix for that hss to be made in wine

since that is the case we are using cabextract ro skip this step

then the extracted files has Launcher.exe which is important for us since its the launcher we need to get authentication for rockstar GTA V

we know that Launcher. exe needs at least vcrun2017 (it has ms-*.dll libs in its root ehich are vcrun2017 libs) and dotnet452 (which shouldn't be required)
Also the Launcher requires at least win7 to be launched, and even setting winver to 7 or 10 it will still saying that the version is not supported, weird.

2019-11-08 23:02 UTC, Klairm commented
Now the rockstar games launcher it's fully working. 

Note that the first launch it will crash, but just ignore it and run it again.

2019-11-09 10:14 UTC, Kreyren commented
@Klairm Can't merge, please resolve the review in file changes.

2019-11-09 10:35 UTC, Kreyren requested changes
@Klairm Can't merge, please resolve the review in file changes.

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        #It requires Dinput8
Provide reference

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        w_override_dlls builtin dinput8
`w_override_dlls native dinput8` is already set by `w_call dinput8` what is the reasoning for builtin?

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        w_package_unsupported_win32
We need a reference here

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        w_download https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe
Can we use checksum or is this being updated to often?

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        w_try mkdir -p "$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher/"
Please make a 'trigger' for this.

i.e: If directory is not present -> Create it

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        # TODO: FIle a winebug -> Requires comdlg32.dll where winelib is not sufficient
Make a new comment in github repository and attempt to make a winebug-like report, once i approve it you will submit it in wine bugzilla if this bug is not known already

again **Do not submit bugs without my approval** i want to make sure that we make it as clear as possible for wine devs to know what is the issue

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        if w_workaround_wine_bug XXXXX; then
This requires winebug reference and comment above with reasoning,

For now add TODO comment above so that we won't forget about this

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +                w_try 7z x "$W_CACHE/$W_PACKAGE/Rockstar-Games-Launcher.exe" "-o/$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher"
Kreytricks specific: Make a trigger for this.

i.e: If package is not extracted -> Extract it (ideally use w_debug() for both scenarios)

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +               # w_try rm "$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher/api-ms-*.dll"
What about this? The rockstar_games_launcher should work without us removing these libraries right?

If not change 7z to not extract these

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +               w_call win10
Use `w_override_app_winenv` instead so that we are not changing wineprefix-wide winenv

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +               w_call vcrun2017
Provide reasoning for this usage in the code with some reference

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        w_call dxvk096
Do we really need dxvk096 for rockstar_games_launcher?

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> -
Why is this here?

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +#-----------------------------------------------------------------
There should be a space, follow the style other verbs are written

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +
Provide `installed_exe1` too

in kreytricks this is used to generate a shortcut

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +        w_call dxvk06
Still this is not sufficient, Why is it needed for rockstar_game_launcher?

2019-11-09 10:35 UTC, Kreyren commented on src/winetricks
> +    }
i meant space between `# ------` and `}` :p

Example:
![image](https://user-images.githubusercontent.com/11302521/68512264-e8cd7780-0245-11ea-8d3d-87f188d45704.png)

2019-11-09 16:26 UTC, Klairm commented on src/winetricks
> +        w_download https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe
It will be updated many times

2019-11-09 16:26 UTC, Klairm commented on src/winetricks
> +        w_override_dlls builtin dinput8
Checked that, dinput8 not really required

2019-11-09 16:27 UTC, Klairm commented on src/winetricks
> +        w_try mkdir -p "$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher/"
Done

2019-11-09 16:40 UTC, Klairm commented on src/winetricks
> -
I don't see it on my code O.o

2019-11-09 19:09 UTC, Klairm commented on src/winetricks
> +        w_package_unsupported_win32
The Rockstar Games Launcher doesn't support 32 bit system -> https://support.rockstargames.com/articles/360035473314/Rockstar-Games-Launcher-system-requirements

2019-11-09 20:47 UTC, Kreyren commented
TODO: verify compatiblity on 32-bit

2019-11-10 01:38 UTC, Kreyren commented
@Klairm This is taking too long so I'm giving you dead line: Nov 11 2019 15:00 CET

if you need a help then ask me

2019-11-12 22:34 UTC, Kreyren commented
@Klairm since i'm mentoring you to contribute in winetricks i've added `Kreytricks specific:` for issues that are kreytricks specific (since kreytricks is oversanitized and has different method to write code)

So i will merge this if you resolve only the issues that are not prefixed with `Kreytricks specific: `

2019-11-14 01:05 UTC, Kreyren commented
Affected by https://bugs.winehq.org/show_bug.cgi?id=48099

2019-11-14 15:52 UTC, Kreyren commented
Affected by https://bugs.winehq.org/show_bug.cgi?id=47794

2019-11-14 15:53 UTC, Kreyren commented
Affected by https://bugs.winehq.org/show_bug.cgi?id=47912

2019-11-14 16:00 UTC, Kreyren commented
Tracking for affected bugs

https://bugs.winehq.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=STAGED&bug_status=REOPENED&bug_status=NEEDINFO&bug_status=RESOLVED&bug_status=CLOSED&list_id=679357&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=DUPLICATE&resolution=WORKSFORME&resolution=ABANDONED&resolution=NOTOURBUG&short_desc=Rockstar%20Games%20Launcher&short_desc_type=allwordssubstr

2019-11-15 00:11 UTC, Kreyren approved these changes
good enough for the beginner

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +    installed_exe1="$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher/Launcher.exe"
This is wrong, it expects windows path not unix!

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +        w_download https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe
@Klairm Provide a comment informing about this fact then

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> -
but i can :p try squashing mby?

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +        w_set_winver win10
Kreytricks specific: Set this per wineapp

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +            echo "Launcher folder not found, creating..."
Kreytricks specific: use printf instead of echo (https://unix.stackexchange.com/a/65819)

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +               # Checking if vcrun2017 is already installed
we dont need an if statement if this sort, but vcrun libs seems to be exported with wine so we should make a tracking for missing features

referencing : https://appdb.winehq.org/objectManager.php?sClass=application&iId=5766 (notice the note)

So make a winebug specifying that rockstar launcher needs foo.dll and attach a WINEDEBUG="-all, +loaddll" so that we can see which libs are called

EDIT: cross-reference the bug with this merge request

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +    installed_file1="C:/Program Files/Rockstar Games/Launcher/Launcher.exe"
there should be a newline after installed_exe1 and above load_...

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +w_metadata rockstar_launcher apps \
there should be a new line above w_metadata

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> -
Unresolved: this is not resolved

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +
This newline shoudn't be there

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +        w_download https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe
Unresolved: this is not resolved

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
> +            for i in $(7z l $W_CACHE/$W_PACKAGE/Rockstar-Games-Launcher.exe)
wrong indentation

2019-11-15 00:11 UTC, Kreyren commented on src/winetricks
>  w_metadata utorrent apps \
There should be a new-line separating w_metadata and #----...

2019-11-15 00:11 UTC, merged